//! IDE localization.
//!
//! UI strings live in `locales/<lang>.conf` files (`key = value` lines,
//! `#` comments) embedded at compile time. The [`Strings`] struct is
//! generated by a macro from a single field list, so a missing key in
//! English is a startup panic and unit tests verify that every locale
//! covers the full key set. Russian text is allowed only in
//! `locales/ru.conf` (project language rule).

use std::sync::OnceLock;

/// Interface language.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Lang {
    /// English (default).
    #[default]
    En,
    /// Russian.
    Ru,
}

const EN_CONF: &str = include_str!("../locales/en.conf");
const RU_CONF: &str = include_str!("../locales/ru.conf");

static EN: OnceLock<Strings> = OnceLock::new();
static RU: OnceLock<Strings> = OnceLock::new();

impl Lang {
    /// Two-letter code used in the settings file.
    pub fn code(self) -> &'static str {
        match self {
            Lang::En => "en",
            Lang::Ru => "ru",
        }
    }

    /// Parse a two-letter code from the settings file.
    pub fn from_code(code: &str) -> Option<Lang> {
        match code {
            "en" => Some(Lang::En),
            "ru" => Some(Lang::Ru),
            _ => None,
        }
    }

    /// Self-name of the language, shown in the language menu.
    pub fn label(self) -> &'static str {
        match self {
            Lang::En => "English",
            Lang::Ru => self.strings().language_self_name,
        }
    }

    /// Localized UI strings for this language.
    ///
    /// Missing Russian keys fall back to English; a missing English key
    /// is a bug and panics on first access.
    pub fn strings(self) -> &'static Strings {
        match self {
            Lang::En => EN.get_or_init(|| Strings::from_conf(EN_CONF, None)),
            Lang::Ru => RU.get_or_init(|| Strings::from_conf(RU_CONF, Some(Lang::En.strings()))),
        }
    }
}

/// Find `key = value` in a conf source and return the trimmed value.
fn lookup(conf: &'static str, key: &str) -> Option<&'static str> {
    conf.lines()
        .filter(|line| !line.trim_start().starts_with('#'))
        .filter_map(|line| line.split_once('='))
        .find(|(k, _)| k.trim() == key)
        .map(|(_, v)| v.trim())
}

macro_rules! define_strings {
    ($($field:ident),* $(,)?) => {
        /// Localized UI strings; one field per key in `locales/*.conf`.
        pub struct Strings {
            $(
                #[doc = "Localized UI string."]
                pub $field: &'static str,
            )*
        }

        impl Strings {
            fn from_conf(conf: &'static str, fallback: Option<&'static Strings>) -> Strings {
                Strings {
                    $(
                        $field: lookup(conf, stringify!($field))
                            .or(fallback.map(|f| f.$field))
                            .unwrap_or_else(|| {
                                panic!("missing localization key `{}`", stringify!($field))
                            }),
                    )*
                }
            }

            /// The full key set, used by locale completeness tests.
            #[cfg(test)]
            fn keys() -> &'static [&'static str] {
                &[$(stringify!($field)),*]
            }
        }
    };
}

define_strings!(
    language_self_name,
    menu_file,
    menu_open_example,
    menu_quit,
    menu_simulation,
    menu_run,
    menu_view,
    menu_theme,
    theme_dark,
    theme_light,
    menu_language,
    menu_help,
    menu_about,
    about_text,
    simulate,
    save,
    ready,
    file_loaded,
    saved,
    write_error,
    open_error,
    no_file_to_save,
    no_file,
    parse_error,
    compile_error,
    sim_error,
    steps_in,
    variables,
    press_simulate,
    tab_plots,
    tab_animation,
    anim_speed,
    anim_rod,
    anim_no_data,
    tab_3d,
    anim_no_bodies,
    params_title,
    inits_title,
    reset_all,
    simulating,
    solver_label,
    tab_diagram,
    diagram_generate,
    diagram_import,
    diagram_hint,
    diagram_palette,
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn english_covers_every_key() {
        // Building without a fallback panics on any missing key.
        let strings = Strings::from_conf(EN_CONF, None);
        assert!(!strings.menu_file.is_empty());
    }

    #[test]
    fn russian_covers_every_key_explicitly() {
        let missing: Vec<&str> = Strings::keys()
            .iter()
            .filter(|key| lookup(RU_CONF, key).is_none())
            .copied()
            .collect();
        assert!(missing.is_empty(), "keys missing in ru.conf: {missing:?}");
    }

    #[test]
    fn codes_round_trip() {
        for lang in [Lang::En, Lang::Ru] {
            assert_eq!(Lang::from_code(lang.code()), Some(lang));
        }
        assert_eq!(Lang::from_code("xx"), None);
    }
}
